# uncomment to preview locally
#theme: "just-the-docs"
remote_theme: dendronhq/dendron-jekyll
title: Heah Hung Xun
logo: "/assets/images/logo.png"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: ""

gh_edit_link: false

# seo
tagline: "There is always a better lightbulb."
description: "I'm a lightbulb"
twitter:
  card: summary
  username: heahhungxun
author:
  twitter: ima_lightbulb

defaults:
  -
    scope:
      path: "notes" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/lightbulb.jpeg"

kramdown:
  math_engine: mathjax
   
const mathBlocks = document.querySelectorAll('script[type^="math/tex"]');
Array.from(mathBlocks).forEach((el) => {
  const tex = el.textContent.replace("% <![CDATA[", "").replace("%]]>", "");
  el.outerHTML = window.katex.renderToString(tex, {
    displayMode: el.type === "math/tex; mode=display",
  });
});
